# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-11 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='data',
            field=models.BinaryField(default=None),
        ),
    ]
